opensrp-server:
  base-url: https://ancs.dev.sid-indonesia.org/opensrp

keycloak:
  realm: ancs-dev
  resource: dev-client
  auth-server-url: https://keycloak.dev.sid-indonesia.org/auth
  principal-attribute: preferred_username
  credentials: 
    secret: "changethis"

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: oauth-client # create this client in the specified keycloak realm with "Service Account Enabled" turned on
            client-secret: "changethis"
        provider:
          keycloak:
            token-uri: https://keycloak.ancs.dev.sid-indonesia.org/auth/realms/${keycloak.realm}/protocol/openid-connect/token
