opensrp-server:
  base-url: https://rdt.stage.sid-indonesia.org/opensrp

keycloak:
  realm: rdt-stage
  resource: dev-client
  auth-server-url: https://keycloak.stage.sid-indonesia.org/auth
  principal-attribute: preferred_username
  credentials: 
    secret: "changethis"

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: oauth-client
            client-secret: "changethis"
        provider:
          keycloak:
            token-uri: https://keycloak.rdt.stage.sid-indonesia.org/auth/realms/${keycloak.realm}/protocol/openid-connect/token
